name: AWS Terraform plan workflow
on:
  push
env:
  AWS_REGION : "eu-west-3"
  TF_API_TOKEN: "${{ secrets.TF_API_TOKEN }}"
# permission can be added at job level or workflow level
permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout
jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::381492150654:role/GithubOIDCRole
          role-session-name: githuboidcrole
          aws-region: ${{ env.AWS_REGION }}
      - name:  check caller identity
        run: |
          aws sts get-caller-identity
      - name: Setup Terraform
      - uses: hashicorp/setup-terraform@v3

      - run: terraform init

      - id: plan
        run: terraform plan -no-color

      - run: echo ${{ steps.plan.outputs.stdout }}
      - run: echo ${{ steps.plan.outputs.stderr }}
      - run: echo ${{ steps.plan.outputs.exitcode }}
